<?php

abstract class Car {
    protected string $speed;
    protected string $color;

    abstract protected function showInfo();
}
class BMW extends Car {

    function __construct($speed)
    {
        $this->speed = $speed;
    }

    public function showInfo()
    {
        // TODO: Change the autogenerated stub
        echo "Speed car: " . $this->speed;
    }
}

$m3 = new BMW(240);
$m3->showInfo();